name: Gmail Notifier

on:
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  workflow_dispatch:  # allow manual run

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write credentials
        run: echo "${{ secrets.GMAIL_CREDENTIALS_JSON }}" > credentials.json

      - name: Write token
        run: echo "${{ secrets.GMAIL_TOKEN_JSON }}" > token.json

      - name: Run Gmail notifier
        env:
          GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
          GMAIL_TOKEN_JSON: ${{ secrets.GMAIL_TOKEN_JSON }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
